apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
  labels:
    app: webapp
spec:
  selector:
    matchLabels:
      app: webapp
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
           maxSurge: 25%
           maxUnavailable: 25%  
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: devops-capstone
        image: michlin0825/devops-capstone:latest
        ports:
        - containerPort: 80
       readinessProbe:
        httpGet:
          path: /
          port: 80 
---
apiVersion: v1
kind: Service
metadata:
  name: webapp-service
spec:
  selector:
    app: webapp
  ports:
  - protocol: TCP
    port: 80
  type: LoadBalancer
---