apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - rolearn: arn:aws:iam::882685904621:role/eks-serv-node-NodeInstanceRole-V9OMY9TJ2RGB
      username: system:node:{{EC2PrivateDNSName}}
      groups:
        - system:bootstrappers
        - system:nodes
# ------------------------------------------Important commands-------------------------
# aws eks update-kubeconfig --name nginxcluster
# kubectl apply -f <filename>
# kubectl delete deploy/web-deployment-blue svc/webapp-service