apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
  labels:
    app: webapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: devops-capstone
        image: michlin0825/devops-capstone
        ports:
        - containerPort: 80
---
kind: Service
apiVersion: v1
metadata:
  name: webapp-service
spec:
  selector:
    app: webapp
  ports:
  - protocol: TCP
    port: 80
  type: LoadBalancer
---